name: CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
permissions:
  contents: read
  packages: write

jobs:
  pipeline:
    uses: HospitalManagementSystem-HMS/Hospital-Management/.github/workflows/frontend-templates.yaml@dev

    with:
      service: "frontend"
      image: "ghcr.io/HospitalManagementSystem-HMS/frontend"
      sonar_key: "HospitalManagementSystem-HMS_frontend_0e9b0218-3c7b-4703-a335-d1c2528ebeb6"
      trigger: ${{ github.event_name }}

    secrets: inherit
